name: fadeplay
description: "A transition-oriented music manager"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Audio support
  just_audio: ^0.10.4
  just_audio_media_kit: ^2.1.0 # for linux / windows
  media_kit_libs_audio: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
